# Tên của quy trình làm việc, sẽ hiển thị trong tab "Actions"
name: Deploy Static Website to Pages

# Quy định khi nào workflow này sẽ chạy
on:
  # Chạy mỗi khi có ai đó push code lên nhánh "main"
  push:
    branches: ["main"]
  # Cho phép bạn chạy workflow này thủ công từ tab Actions
  workflow_dispatch:

# Cấp quyền cho workflow để nó có thể ghi vào repository (để deploy)
permissions:
  contents: read
  pages: write
  id-token: write

# Các công việc (jobs) cần thực hiện. Có thể chạy song song hoặc tuần tự.
jobs:
  # Định nghĩa một job tên là "deploy"
  deploy:
    # Môi trường deploy là GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Chỉ định máy ảo để chạy job này (sử dụng Ubuntu phiên bản mới nhất)
    runs-on: ubuntu-latest
    # Các bước (steps) trong job "deploy"
    steps:
      # Bước 1: Lấy mã nguồn từ repository về máy ảo
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cấu hình môi trường cho GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Bước 3: "Build" website (tải các file tĩnh lên một thư mục tạm)
      # Đối với HTML tĩnh, chúng ta chỉ cần chỉ định thư mục gốc là đủ
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Tải lên nội dung từ thư mục gốc của dự án
          path: '.'

      # Bước 4: Deploy website lên GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
